spring:
  profiles:
    active:
    - dev
---

spring:
  profiles: dev
  application:
    name: microcloud-member-client    # 定义应用项目的名称
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-config.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 30 # 续约更新时间间隔（默认30秒） —— 心跳
    lease-expiration-duration-in-seconds: 90 # 续约到期时间（默认90秒），表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    prefer-ip-address: true # 地址栏上使用ip地址进行显示
    instance-id: member-8001.com # 在信息中显示主机名称 

