spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microcloud-eureka-config    # 定义应用项目的名称
info: 
  app.name: microcloud-eureka-config-1
  app.version: v1.0.0
